version: 2

sources:
  - name: raw
    description: raw data from GreenWeez
    schema: gz_raw_data
    tables:

      - name: products
        description: raw data for all products sold
        identifier: raw_gz_product
        columns:
          - name: products_id
            tests:
              - unique
              - not_null

          
      - name: sales
        description: raw data for all sales
        identifier: raw_gz_sales
        columns: 
          - name: "(orders_id || '_' || pdt_id)"
            tests:
              - unique
              - not_null

      - name: ship
        description: raw data for shipping
        identifier: raw_gz_ship
        columns:
          - name: orders_id
            tests:
              - unique
              - not_null